spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
  datasource:
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/car_shop?createDatabaseIfNotExist=true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: warn
        sql: warn
      nodeValue: WARN
    blog: WARN
